// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ironserver/proto/main.proto
// Protobuf Java Version: 4.33.1

package com.decduck3.ironcomputing.proto;

@com.google.protobuf.Generated
public final class Main extends com.google.protobuf.GeneratedFile {
  private Main() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "Main");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.decduck3.ironcomputing.proto.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ERROR = 0;</code>
     */
    ERROR(0),
    /**
     * <pre>
     * Uploads and deletes WASM binaries
     * </pre>
     *
     * <code>UPLOAD_FIRMWARE = 1;</code>
     */
    UPLOAD_FIRMWARE(1),
    /**
     * <code>DELETE_FIRMWARE = 2;</code>
     */
    DELETE_FIRMWARE(2),
    /**
     * <pre>
     * Create/configure/delete
     * </pre>
     *
     * <code>CREATE_VM = 3;</code>
     */
    CREATE_VM(3),
    /**
     * <code>CONFIGURE_VM = 4;</code>
     */
    CONFIGURE_VM(4),
    /**
     * <code>DELETE_VM = 5;</code>
     */
    DELETE_VM(5),
    /**
     * <pre>
     * Create or delete hard drives
     * </pre>
     *
     * <code>CREATE_HARDDISK = 6;</code>
     */
    CREATE_HARDDISK(6),
    /**
     * <code>DELETE_HARDDISK = 7;</code>
     */
    DELETE_HARDDISK(7),
    /**
     * <code>PING = 8;</code>
     */
    PING(8),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 1,
        /* suffix= */ "",
        "MessageType");
    }
    /**
     * <code>ERROR = 0;</code>
     */
    public static final int ERROR_VALUE = 0;
    /**
     * <pre>
     * Uploads and deletes WASM binaries
     * </pre>
     *
     * <code>UPLOAD_FIRMWARE = 1;</code>
     */
    public static final int UPLOAD_FIRMWARE_VALUE = 1;
    /**
     * <code>DELETE_FIRMWARE = 2;</code>
     */
    public static final int DELETE_FIRMWARE_VALUE = 2;
    /**
     * <pre>
     * Create/configure/delete
     * </pre>
     *
     * <code>CREATE_VM = 3;</code>
     */
    public static final int CREATE_VM_VALUE = 3;
    /**
     * <code>CONFIGURE_VM = 4;</code>
     */
    public static final int CONFIGURE_VM_VALUE = 4;
    /**
     * <code>DELETE_VM = 5;</code>
     */
    public static final int DELETE_VM_VALUE = 5;
    /**
     * <pre>
     * Create or delete hard drives
     * </pre>
     *
     * <code>CREATE_HARDDISK = 6;</code>
     */
    public static final int CREATE_HARDDISK_VALUE = 6;
    /**
     * <code>DELETE_HARDDISK = 7;</code>
     */
    public static final int DELETE_HARDDISK_VALUE = 7;
    /**
     * <code>PING = 8;</code>
     */
    public static final int PING_VALUE = 8;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return ERROR;
        case 1: return UPLOAD_FIRMWARE;
        case 2: return DELETE_FIRMWARE;
        case 3: return CREATE_VM;
        case 4: return CONFIGURE_VM;
        case 5: return DELETE_VM;
        case 6: return CREATE_HARDDISK;
        case 7: return DELETE_HARDDISK;
        case 8: return PING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.decduck3.ironcomputing.proto.Main.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.decduck3.ironcomputing.proto.MessageType)
  }

  public interface JavaRustOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.decduck3.ironcomputing.proto.JavaRust)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>.com.decduck3.ironcomputing.proto.MessageType message_type = 2;</code>
     * @return The enum numeric value on the wire for messageType.
     */
    int getMessageTypeValue();
    /**
     * <code>.com.decduck3.ironcomputing.proto.MessageType message_type = 2;</code>
     * @return The messageType.
     */
    com.decduck3.ironcomputing.proto.Main.MessageType getMessageType();

    /**
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code com.decduck3.ironcomputing.proto.JavaRust}
   */
  public static final class JavaRust extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.decduck3.ironcomputing.proto.JavaRust)
      JavaRustOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 1,
        /* suffix= */ "",
        "JavaRust");
    }
    // Use JavaRust.newBuilder() to construct.
    private JavaRust(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private JavaRust() {
      id_ = "";
      messageType_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.decduck3.ironcomputing.proto.Main.internal_static_com_decduck3_ironcomputing_proto_JavaRust_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.decduck3.ironcomputing.proto.Main.internal_static_com_decduck3_ironcomputing_proto_JavaRust_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.decduck3.ironcomputing.proto.Main.JavaRust.class, com.decduck3.ironcomputing.proto.Main.JavaRust.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_TYPE_FIELD_NUMBER = 2;
    private int messageType_ = 0;
    /**
     * <code>.com.decduck3.ironcomputing.proto.MessageType message_type = 2;</code>
     * @return The enum numeric value on the wire for messageType.
     */
    @java.lang.Override public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <code>.com.decduck3.ironcomputing.proto.MessageType message_type = 2;</code>
     * @return The messageType.
     */
    @java.lang.Override public com.decduck3.ironcomputing.proto.Main.MessageType getMessageType() {
      com.decduck3.ironcomputing.proto.Main.MessageType result = com.decduck3.ironcomputing.proto.Main.MessageType.forNumber(messageType_);
      return result == null ? com.decduck3.ironcomputing.proto.Main.MessageType.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
      }
      if (messageType_ != com.decduck3.ironcomputing.proto.Main.MessageType.ERROR.getNumber()) {
        output.writeEnum(2, messageType_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(3, data_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
      }
      if (messageType_ != com.decduck3.ironcomputing.proto.Main.MessageType.ERROR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, messageType_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.decduck3.ironcomputing.proto.Main.JavaRust)) {
        return super.equals(obj);
      }
      com.decduck3.ironcomputing.proto.Main.JavaRust other = (com.decduck3.ironcomputing.proto.Main.JavaRust) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (messageType_ != other.messageType_) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + MESSAGE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + messageType_;
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.decduck3.ironcomputing.proto.Main.JavaRust parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.decduck3.ironcomputing.proto.Main.JavaRust parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.decduck3.ironcomputing.proto.Main.JavaRust parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.decduck3.ironcomputing.proto.Main.JavaRust parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.decduck3.ironcomputing.proto.Main.JavaRust parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.decduck3.ironcomputing.proto.Main.JavaRust parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.decduck3.ironcomputing.proto.Main.JavaRust parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.decduck3.ironcomputing.proto.Main.JavaRust parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.decduck3.ironcomputing.proto.Main.JavaRust parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.decduck3.ironcomputing.proto.Main.JavaRust parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.decduck3.ironcomputing.proto.Main.JavaRust parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.decduck3.ironcomputing.proto.Main.JavaRust parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.decduck3.ironcomputing.proto.Main.JavaRust prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.decduck3.ironcomputing.proto.JavaRust}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.decduck3.ironcomputing.proto.JavaRust)
        com.decduck3.ironcomputing.proto.Main.JavaRustOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.decduck3.ironcomputing.proto.Main.internal_static_com_decduck3_ironcomputing_proto_JavaRust_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.decduck3.ironcomputing.proto.Main.internal_static_com_decduck3_ironcomputing_proto_JavaRust_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.decduck3.ironcomputing.proto.Main.JavaRust.class, com.decduck3.ironcomputing.proto.Main.JavaRust.Builder.class);
      }

      // Construct using com.decduck3.ironcomputing.proto.Main.JavaRust.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        messageType_ = 0;
        data_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.decduck3.ironcomputing.proto.Main.internal_static_com_decduck3_ironcomputing_proto_JavaRust_descriptor;
      }

      @java.lang.Override
      public com.decduck3.ironcomputing.proto.Main.JavaRust getDefaultInstanceForType() {
        return com.decduck3.ironcomputing.proto.Main.JavaRust.getDefaultInstance();
      }

      @java.lang.Override
      public com.decduck3.ironcomputing.proto.Main.JavaRust build() {
        com.decduck3.ironcomputing.proto.Main.JavaRust result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.decduck3.ironcomputing.proto.Main.JavaRust buildPartial() {
        com.decduck3.ironcomputing.proto.Main.JavaRust result = new com.decduck3.ironcomputing.proto.Main.JavaRust(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.decduck3.ironcomputing.proto.Main.JavaRust result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.messageType_ = messageType_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.data_ = data_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.decduck3.ironcomputing.proto.Main.JavaRust) {
          return mergeFrom((com.decduck3.ironcomputing.proto.Main.JavaRust)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.decduck3.ironcomputing.proto.Main.JavaRust other) {
        if (other == com.decduck3.ironcomputing.proto.Main.JavaRust.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.messageType_ != 0) {
          setMessageTypeValue(other.getMessageTypeValue());
        }
        if (!other.getData().isEmpty()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                messageType_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                data_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int messageType_ = 0;
      /**
       * <code>.com.decduck3.ironcomputing.proto.MessageType message_type = 2;</code>
       * @return The enum numeric value on the wire for messageType.
       */
      @java.lang.Override public int getMessageTypeValue() {
        return messageType_;
      }
      /**
       * <code>.com.decduck3.ironcomputing.proto.MessageType message_type = 2;</code>
       * @param value The enum numeric value on the wire for messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageTypeValue(int value) {
        messageType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.com.decduck3.ironcomputing.proto.MessageType message_type = 2;</code>
       * @return The messageType.
       */
      @java.lang.Override
      public com.decduck3.ironcomputing.proto.Main.MessageType getMessageType() {
        com.decduck3.ironcomputing.proto.Main.MessageType result = com.decduck3.ironcomputing.proto.Main.MessageType.forNumber(messageType_);
        return result == null ? com.decduck3.ironcomputing.proto.Main.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.decduck3.ironcomputing.proto.MessageType message_type = 2;</code>
       * @param value The messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageType(com.decduck3.ironcomputing.proto.Main.MessageType value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000002;
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.decduck3.ironcomputing.proto.MessageType message_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        messageType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 3;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 3;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.decduck3.ironcomputing.proto.JavaRust)
    }

    // @@protoc_insertion_point(class_scope:com.decduck3.ironcomputing.proto.JavaRust)
    private static final com.decduck3.ironcomputing.proto.Main.JavaRust DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.decduck3.ironcomputing.proto.Main.JavaRust();
    }

    public static com.decduck3.ironcomputing.proto.Main.JavaRust getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JavaRust>
        PARSER = new com.google.protobuf.AbstractParser<JavaRust>() {
      @java.lang.Override
      public JavaRust parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<JavaRust> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JavaRust> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.decduck3.ironcomputing.proto.Main.JavaRust getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RustJavaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.decduck3.ironcomputing.proto.RustJava)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>.com.decduck3.ironcomputing.proto.MessageType message_type = 2;</code>
     * @return The enum numeric value on the wire for messageType.
     */
    int getMessageTypeValue();
    /**
     * <code>.com.decduck3.ironcomputing.proto.MessageType message_type = 2;</code>
     * @return The messageType.
     */
    com.decduck3.ironcomputing.proto.Main.MessageType getMessageType();

    /**
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code com.decduck3.ironcomputing.proto.RustJava}
   */
  public static final class RustJava extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.decduck3.ironcomputing.proto.RustJava)
      RustJavaOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 1,
        /* suffix= */ "",
        "RustJava");
    }
    // Use RustJava.newBuilder() to construct.
    private RustJava(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RustJava() {
      id_ = "";
      messageType_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.decduck3.ironcomputing.proto.Main.internal_static_com_decduck3_ironcomputing_proto_RustJava_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.decduck3.ironcomputing.proto.Main.internal_static_com_decduck3_ironcomputing_proto_RustJava_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.decduck3.ironcomputing.proto.Main.RustJava.class, com.decduck3.ironcomputing.proto.Main.RustJava.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_TYPE_FIELD_NUMBER = 2;
    private int messageType_ = 0;
    /**
     * <code>.com.decduck3.ironcomputing.proto.MessageType message_type = 2;</code>
     * @return The enum numeric value on the wire for messageType.
     */
    @java.lang.Override public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <code>.com.decduck3.ironcomputing.proto.MessageType message_type = 2;</code>
     * @return The messageType.
     */
    @java.lang.Override public com.decduck3.ironcomputing.proto.Main.MessageType getMessageType() {
      com.decduck3.ironcomputing.proto.Main.MessageType result = com.decduck3.ironcomputing.proto.Main.MessageType.forNumber(messageType_);
      return result == null ? com.decduck3.ironcomputing.proto.Main.MessageType.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
      }
      if (messageType_ != com.decduck3.ironcomputing.proto.Main.MessageType.ERROR.getNumber()) {
        output.writeEnum(2, messageType_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(3, data_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
      }
      if (messageType_ != com.decduck3.ironcomputing.proto.Main.MessageType.ERROR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, messageType_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.decduck3.ironcomputing.proto.Main.RustJava)) {
        return super.equals(obj);
      }
      com.decduck3.ironcomputing.proto.Main.RustJava other = (com.decduck3.ironcomputing.proto.Main.RustJava) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (messageType_ != other.messageType_) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + MESSAGE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + messageType_;
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.decduck3.ironcomputing.proto.Main.RustJava parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.decduck3.ironcomputing.proto.Main.RustJava parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.decduck3.ironcomputing.proto.Main.RustJava parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.decduck3.ironcomputing.proto.Main.RustJava parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.decduck3.ironcomputing.proto.Main.RustJava parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.decduck3.ironcomputing.proto.Main.RustJava parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.decduck3.ironcomputing.proto.Main.RustJava parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.decduck3.ironcomputing.proto.Main.RustJava parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.decduck3.ironcomputing.proto.Main.RustJava parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.decduck3.ironcomputing.proto.Main.RustJava parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.decduck3.ironcomputing.proto.Main.RustJava parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.decduck3.ironcomputing.proto.Main.RustJava parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.decduck3.ironcomputing.proto.Main.RustJava prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.decduck3.ironcomputing.proto.RustJava}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.decduck3.ironcomputing.proto.RustJava)
        com.decduck3.ironcomputing.proto.Main.RustJavaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.decduck3.ironcomputing.proto.Main.internal_static_com_decduck3_ironcomputing_proto_RustJava_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.decduck3.ironcomputing.proto.Main.internal_static_com_decduck3_ironcomputing_proto_RustJava_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.decduck3.ironcomputing.proto.Main.RustJava.class, com.decduck3.ironcomputing.proto.Main.RustJava.Builder.class);
      }

      // Construct using com.decduck3.ironcomputing.proto.Main.RustJava.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        messageType_ = 0;
        data_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.decduck3.ironcomputing.proto.Main.internal_static_com_decduck3_ironcomputing_proto_RustJava_descriptor;
      }

      @java.lang.Override
      public com.decduck3.ironcomputing.proto.Main.RustJava getDefaultInstanceForType() {
        return com.decduck3.ironcomputing.proto.Main.RustJava.getDefaultInstance();
      }

      @java.lang.Override
      public com.decduck3.ironcomputing.proto.Main.RustJava build() {
        com.decduck3.ironcomputing.proto.Main.RustJava result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.decduck3.ironcomputing.proto.Main.RustJava buildPartial() {
        com.decduck3.ironcomputing.proto.Main.RustJava result = new com.decduck3.ironcomputing.proto.Main.RustJava(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.decduck3.ironcomputing.proto.Main.RustJava result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.messageType_ = messageType_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.data_ = data_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.decduck3.ironcomputing.proto.Main.RustJava) {
          return mergeFrom((com.decduck3.ironcomputing.proto.Main.RustJava)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.decduck3.ironcomputing.proto.Main.RustJava other) {
        if (other == com.decduck3.ironcomputing.proto.Main.RustJava.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.messageType_ != 0) {
          setMessageTypeValue(other.getMessageTypeValue());
        }
        if (!other.getData().isEmpty()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                messageType_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                data_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int messageType_ = 0;
      /**
       * <code>.com.decduck3.ironcomputing.proto.MessageType message_type = 2;</code>
       * @return The enum numeric value on the wire for messageType.
       */
      @java.lang.Override public int getMessageTypeValue() {
        return messageType_;
      }
      /**
       * <code>.com.decduck3.ironcomputing.proto.MessageType message_type = 2;</code>
       * @param value The enum numeric value on the wire for messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageTypeValue(int value) {
        messageType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.com.decduck3.ironcomputing.proto.MessageType message_type = 2;</code>
       * @return The messageType.
       */
      @java.lang.Override
      public com.decduck3.ironcomputing.proto.Main.MessageType getMessageType() {
        com.decduck3.ironcomputing.proto.Main.MessageType result = com.decduck3.ironcomputing.proto.Main.MessageType.forNumber(messageType_);
        return result == null ? com.decduck3.ironcomputing.proto.Main.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.decduck3.ironcomputing.proto.MessageType message_type = 2;</code>
       * @param value The messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageType(com.decduck3.ironcomputing.proto.Main.MessageType value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000002;
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.decduck3.ironcomputing.proto.MessageType message_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        messageType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 3;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 3;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.decduck3.ironcomputing.proto.RustJava)
    }

    // @@protoc_insertion_point(class_scope:com.decduck3.ironcomputing.proto.RustJava)
    private static final com.decduck3.ironcomputing.proto.Main.RustJava DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.decduck3.ironcomputing.proto.Main.RustJava();
    }

    public static com.decduck3.ironcomputing.proto.Main.RustJava getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RustJava>
        PARSER = new com.google.protobuf.AbstractParser<RustJava>() {
      @java.lang.Override
      public RustJava parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RustJava> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RustJava> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.decduck3.ironcomputing.proto.Main.RustJava getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_decduck3_ironcomputing_proto_JavaRust_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_decduck3_ironcomputing_proto_JavaRust_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_decduck3_ironcomputing_proto_RustJava_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_decduck3_ironcomputing_proto_RustJava_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033ironserver/proto/main.proto\022 com.decdu" +
      "ck3.ironcomputing.proto\"i\n\010JavaRust\022\n\n\002i" +
      "d\030\001 \001(\t\022C\n\014message_type\030\002 \001(\0162-.com.decd" +
      "uck3.ironcomputing.proto.MessageType\022\014\n\004" +
      "data\030\003 \001(\014\"i\n\010RustJava\022\n\n\002id\030\001 \001(\t\022C\n\014me" +
      "ssage_type\030\002 \001(\0162-.com.decduck3.ironcomp" +
      "uting.proto.MessageType\022\014\n\004data\030\003 \001(\014*\246\001" +
      "\n\013MessageType\022\t\n\005ERROR\020\000\022\023\n\017UPLOAD_FIRMW" +
      "ARE\020\001\022\023\n\017DELETE_FIRMWARE\020\002\022\r\n\tCREATE_VM\020" +
      "\003\022\020\n\014CONFIGURE_VM\020\004\022\r\n\tDELETE_VM\020\005\022\023\n\017CR" +
      "EATE_HARDDISK\020\006\022\023\n\017DELETE_HARDDISK\020\007\022\010\n\004" +
      "PING\020\010b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_decduck3_ironcomputing_proto_JavaRust_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_com_decduck3_ironcomputing_proto_JavaRust_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_decduck3_ironcomputing_proto_JavaRust_descriptor,
        new java.lang.String[] { "Id", "MessageType", "Data", });
    internal_static_com_decduck3_ironcomputing_proto_RustJava_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_com_decduck3_ironcomputing_proto_RustJava_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_decduck3_ironcomputing_proto_RustJava_descriptor,
        new java.lang.String[] { "Id", "MessageType", "Data", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
