// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ironserver/proto/upload.proto
// Protobuf Java Version: 4.33.1

package com.decduck3.ironcomputing.proto;

@com.google.protobuf.Generated
public final class Upload extends com.google.protobuf.GeneratedFile {
  private Upload() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "Upload");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MultipartUploadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.decduck3.ironcomputing.proto.MultipartUpload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string upload_id = 1;</code>
     * @return The uploadId.
     */
    java.lang.String getUploadId();
    /**
     * <code>string upload_id = 1;</code>
     * @return The bytes for uploadId.
     */
    com.google.protobuf.ByteString
        getUploadIdBytes();

    /**
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>bool next = 3;</code>
     * @return The next.
     */
    boolean getNext();
  }
  /**
   * Protobuf type {@code com.decduck3.ironcomputing.proto.MultipartUpload}
   */
  public static final class MultipartUpload extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.decduck3.ironcomputing.proto.MultipartUpload)
      MultipartUploadOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 1,
        /* suffix= */ "",
        "MultipartUpload");
    }
    // Use MultipartUpload.newBuilder() to construct.
    private MultipartUpload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MultipartUpload() {
      uploadId_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.decduck3.ironcomputing.proto.Upload.internal_static_com_decduck3_ironcomputing_proto_MultipartUpload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.decduck3.ironcomputing.proto.Upload.internal_static_com_decduck3_ironcomputing_proto_MultipartUpload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.decduck3.ironcomputing.proto.Upload.MultipartUpload.class, com.decduck3.ironcomputing.proto.Upload.MultipartUpload.Builder.class);
    }

    public static final int UPLOAD_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object uploadId_ = "";
    /**
     * <code>string upload_id = 1;</code>
     * @return The uploadId.
     */
    @java.lang.Override
    public java.lang.String getUploadId() {
      java.lang.Object ref = uploadId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uploadId_ = s;
        return s;
      }
    }
    /**
     * <code>string upload_id = 1;</code>
     * @return The bytes for uploadId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUploadIdBytes() {
      java.lang.Object ref = uploadId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uploadId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int NEXT_FIELD_NUMBER = 3;
    private boolean next_ = false;
    /**
     * <code>bool next = 3;</code>
     * @return The next.
     */
    @java.lang.Override
    public boolean getNext() {
      return next_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uploadId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, uploadId_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
      if (next_ != false) {
        output.writeBool(3, next_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uploadId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, uploadId_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      if (next_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, next_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.decduck3.ironcomputing.proto.Upload.MultipartUpload)) {
        return super.equals(obj);
      }
      com.decduck3.ironcomputing.proto.Upload.MultipartUpload other = (com.decduck3.ironcomputing.proto.Upload.MultipartUpload) obj;

      if (!getUploadId()
          .equals(other.getUploadId())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (getNext()
          != other.getNext()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UPLOAD_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUploadId().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + NEXT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getNext());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.decduck3.ironcomputing.proto.Upload.MultipartUpload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.decduck3.ironcomputing.proto.Upload.MultipartUpload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.decduck3.ironcomputing.proto.Upload.MultipartUpload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.decduck3.ironcomputing.proto.Upload.MultipartUpload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.decduck3.ironcomputing.proto.Upload.MultipartUpload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.decduck3.ironcomputing.proto.Upload.MultipartUpload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.decduck3.ironcomputing.proto.Upload.MultipartUpload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.decduck3.ironcomputing.proto.Upload.MultipartUpload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.decduck3.ironcomputing.proto.Upload.MultipartUpload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.decduck3.ironcomputing.proto.Upload.MultipartUpload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.decduck3.ironcomputing.proto.Upload.MultipartUpload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.decduck3.ironcomputing.proto.Upload.MultipartUpload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.decduck3.ironcomputing.proto.Upload.MultipartUpload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.decduck3.ironcomputing.proto.MultipartUpload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.decduck3.ironcomputing.proto.MultipartUpload)
        com.decduck3.ironcomputing.proto.Upload.MultipartUploadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.decduck3.ironcomputing.proto.Upload.internal_static_com_decduck3_ironcomputing_proto_MultipartUpload_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.decduck3.ironcomputing.proto.Upload.internal_static_com_decduck3_ironcomputing_proto_MultipartUpload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.decduck3.ironcomputing.proto.Upload.MultipartUpload.class, com.decduck3.ironcomputing.proto.Upload.MultipartUpload.Builder.class);
      }

      // Construct using com.decduck3.ironcomputing.proto.Upload.MultipartUpload.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        uploadId_ = "";
        data_ = com.google.protobuf.ByteString.EMPTY;
        next_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.decduck3.ironcomputing.proto.Upload.internal_static_com_decduck3_ironcomputing_proto_MultipartUpload_descriptor;
      }

      @java.lang.Override
      public com.decduck3.ironcomputing.proto.Upload.MultipartUpload getDefaultInstanceForType() {
        return com.decduck3.ironcomputing.proto.Upload.MultipartUpload.getDefaultInstance();
      }

      @java.lang.Override
      public com.decduck3.ironcomputing.proto.Upload.MultipartUpload build() {
        com.decduck3.ironcomputing.proto.Upload.MultipartUpload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.decduck3.ironcomputing.proto.Upload.MultipartUpload buildPartial() {
        com.decduck3.ironcomputing.proto.Upload.MultipartUpload result = new com.decduck3.ironcomputing.proto.Upload.MultipartUpload(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.decduck3.ironcomputing.proto.Upload.MultipartUpload result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.uploadId_ = uploadId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.data_ = data_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.next_ = next_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.decduck3.ironcomputing.proto.Upload.MultipartUpload) {
          return mergeFrom((com.decduck3.ironcomputing.proto.Upload.MultipartUpload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.decduck3.ironcomputing.proto.Upload.MultipartUpload other) {
        if (other == com.decduck3.ironcomputing.proto.Upload.MultipartUpload.getDefaultInstance()) return this;
        if (!other.getUploadId().isEmpty()) {
          uploadId_ = other.uploadId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getData().isEmpty()) {
          setData(other.getData());
        }
        if (other.getNext() != false) {
          setNext(other.getNext());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                uploadId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                data_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                next_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object uploadId_ = "";
      /**
       * <code>string upload_id = 1;</code>
       * @return The uploadId.
       */
      public java.lang.String getUploadId() {
        java.lang.Object ref = uploadId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uploadId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string upload_id = 1;</code>
       * @return The bytes for uploadId.
       */
      public com.google.protobuf.ByteString
          getUploadIdBytes() {
        java.lang.Object ref = uploadId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uploadId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string upload_id = 1;</code>
       * @param value The uploadId to set.
       * @return This builder for chaining.
       */
      public Builder setUploadId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        uploadId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string upload_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUploadId() {
        uploadId_ = getDefaultInstance().getUploadId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string upload_id = 1;</code>
       * @param value The bytes for uploadId to set.
       * @return This builder for chaining.
       */
      public Builder setUploadIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        uploadId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 2;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private boolean next_ ;
      /**
       * <code>bool next = 3;</code>
       * @return The next.
       */
      @java.lang.Override
      public boolean getNext() {
        return next_;
      }
      /**
       * <code>bool next = 3;</code>
       * @param value The next to set.
       * @return This builder for chaining.
       */
      public Builder setNext(boolean value) {

        next_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool next = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNext() {
        bitField0_ = (bitField0_ & ~0x00000004);
        next_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.decduck3.ironcomputing.proto.MultipartUpload)
    }

    // @@protoc_insertion_point(class_scope:com.decduck3.ironcomputing.proto.MultipartUpload)
    private static final com.decduck3.ironcomputing.proto.Upload.MultipartUpload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.decduck3.ironcomputing.proto.Upload.MultipartUpload();
    }

    public static com.decduck3.ironcomputing.proto.Upload.MultipartUpload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MultipartUpload>
        PARSER = new com.google.protobuf.AbstractParser<MultipartUpload>() {
      @java.lang.Override
      public MultipartUpload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MultipartUpload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MultipartUpload> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.decduck3.ironcomputing.proto.Upload.MultipartUpload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_decduck3_ironcomputing_proto_MultipartUpload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_decduck3_ironcomputing_proto_MultipartUpload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035ironserver/proto/upload.proto\022 com.dec" +
      "duck3.ironcomputing.proto\"@\n\017MultipartUp" +
      "load\022\021\n\tupload_id\030\001 \001(\t\022\014\n\004data\030\002 \001(\014\022\014\n" +
      "\004next\030\003 \001(\010b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_decduck3_ironcomputing_proto_MultipartUpload_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_com_decduck3_ironcomputing_proto_MultipartUpload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_decduck3_ironcomputing_proto_MultipartUpload_descriptor,
        new java.lang.String[] { "UploadId", "Data", "Next", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
