// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ironserver/proto/vm.proto
// Protobuf Java Version: 4.33.1

package com.decduck3.ironcomputing.proto;

@com.google.protobuf.Generated
public final class Vm extends com.google.protobuf.GeneratedFile {
  private Vm() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "Vm");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VMConfigurationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.decduck3.ironcomputing.proto.VMConfiguration)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string vm_id = 1;</code>
     * @return Whether the vmId field is set.
     */
    boolean hasVmId();
    /**
     * <code>optional string vm_id = 1;</code>
     * @return The vmId.
     */
    java.lang.String getVmId();
    /**
     * <code>optional string vm_id = 1;</code>
     * @return The bytes for vmId.
     */
    com.google.protobuf.ByteString
        getVmIdBytes();

    /**
     * <code>string firmware_id = 2;</code>
     * @return The firmwareId.
     */
    java.lang.String getFirmwareId();
    /**
     * <code>string firmware_id = 2;</code>
     * @return The bytes for firmwareId.
     */
    com.google.protobuf.ByteString
        getFirmwareIdBytes();

    /**
     * <code>uint64 ram_size = 3;</code>
     * @return The ramSize.
     */
    long getRamSize();

    /**
     * <code>repeated string harddisk_ids = 4;</code>
     * @return A list containing the harddiskIds.
     */
    java.util.List<java.lang.String>
        getHarddiskIdsList();
    /**
     * <code>repeated string harddisk_ids = 4;</code>
     * @return The count of harddiskIds.
     */
    int getHarddiskIdsCount();
    /**
     * <code>repeated string harddisk_ids = 4;</code>
     * @param index The index of the element to return.
     * @return The harddiskIds at the given index.
     */
    java.lang.String getHarddiskIds(int index);
    /**
     * <code>repeated string harddisk_ids = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the harddiskIds at the given index.
     */
    com.google.protobuf.ByteString
        getHarddiskIdsBytes(int index);
  }
  /**
   * Protobuf type {@code com.decduck3.ironcomputing.proto.VMConfiguration}
   */
  public static final class VMConfiguration extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.decduck3.ironcomputing.proto.VMConfiguration)
      VMConfigurationOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 1,
        /* suffix= */ "",
        "VMConfiguration");
    }
    // Use VMConfiguration.newBuilder() to construct.
    private VMConfiguration(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private VMConfiguration() {
      vmId_ = "";
      firmwareId_ = "";
      harddiskIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.decduck3.ironcomputing.proto.Vm.internal_static_com_decduck3_ironcomputing_proto_VMConfiguration_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.decduck3.ironcomputing.proto.Vm.internal_static_com_decduck3_ironcomputing_proto_VMConfiguration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.decduck3.ironcomputing.proto.Vm.VMConfiguration.class, com.decduck3.ironcomputing.proto.Vm.VMConfiguration.Builder.class);
    }

    private int bitField0_;
    public static final int VM_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object vmId_ = "";
    /**
     * <code>optional string vm_id = 1;</code>
     * @return Whether the vmId field is set.
     */
    @java.lang.Override
    public boolean hasVmId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string vm_id = 1;</code>
     * @return The vmId.
     */
    @java.lang.Override
    public java.lang.String getVmId() {
      java.lang.Object ref = vmId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vmId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string vm_id = 1;</code>
     * @return The bytes for vmId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVmIdBytes() {
      java.lang.Object ref = vmId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vmId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIRMWARE_ID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object firmwareId_ = "";
    /**
     * <code>string firmware_id = 2;</code>
     * @return The firmwareId.
     */
    @java.lang.Override
    public java.lang.String getFirmwareId() {
      java.lang.Object ref = firmwareId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firmwareId_ = s;
        return s;
      }
    }
    /**
     * <code>string firmware_id = 2;</code>
     * @return The bytes for firmwareId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirmwareIdBytes() {
      java.lang.Object ref = firmwareId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firmwareId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RAM_SIZE_FIELD_NUMBER = 3;
    private long ramSize_ = 0L;
    /**
     * <code>uint64 ram_size = 3;</code>
     * @return The ramSize.
     */
    @java.lang.Override
    public long getRamSize() {
      return ramSize_;
    }

    public static final int HARDDISK_IDS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList harddiskIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string harddisk_ids = 4;</code>
     * @return A list containing the harddiskIds.
     */
    public com.google.protobuf.ProtocolStringList
        getHarddiskIdsList() {
      return harddiskIds_;
    }
    /**
     * <code>repeated string harddisk_ids = 4;</code>
     * @return The count of harddiskIds.
     */
    public int getHarddiskIdsCount() {
      return harddiskIds_.size();
    }
    /**
     * <code>repeated string harddisk_ids = 4;</code>
     * @param index The index of the element to return.
     * @return The harddiskIds at the given index.
     */
    public java.lang.String getHarddiskIds(int index) {
      return harddiskIds_.get(index);
    }
    /**
     * <code>repeated string harddisk_ids = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the harddiskIds at the given index.
     */
    public com.google.protobuf.ByteString
        getHarddiskIdsBytes(int index) {
      return harddiskIds_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, vmId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(firmwareId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, firmwareId_);
      }
      if (ramSize_ != 0L) {
        output.writeUInt64(3, ramSize_);
      }
      for (int i = 0; i < harddiskIds_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, harddiskIds_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, vmId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(firmwareId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, firmwareId_);
      }
      if (ramSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, ramSize_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < harddiskIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(harddiskIds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getHarddiskIdsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.decduck3.ironcomputing.proto.Vm.VMConfiguration)) {
        return super.equals(obj);
      }
      com.decduck3.ironcomputing.proto.Vm.VMConfiguration other = (com.decduck3.ironcomputing.proto.Vm.VMConfiguration) obj;

      if (hasVmId() != other.hasVmId()) return false;
      if (hasVmId()) {
        if (!getVmId()
            .equals(other.getVmId())) return false;
      }
      if (!getFirmwareId()
          .equals(other.getFirmwareId())) return false;
      if (getRamSize()
          != other.getRamSize()) return false;
      if (!getHarddiskIdsList()
          .equals(other.getHarddiskIdsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVmId()) {
        hash = (37 * hash) + VM_ID_FIELD_NUMBER;
        hash = (53 * hash) + getVmId().hashCode();
      }
      hash = (37 * hash) + FIRMWARE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getFirmwareId().hashCode();
      hash = (37 * hash) + RAM_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRamSize());
      if (getHarddiskIdsCount() > 0) {
        hash = (37 * hash) + HARDDISK_IDS_FIELD_NUMBER;
        hash = (53 * hash) + getHarddiskIdsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.decduck3.ironcomputing.proto.Vm.VMConfiguration parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.decduck3.ironcomputing.proto.Vm.VMConfiguration parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.decduck3.ironcomputing.proto.Vm.VMConfiguration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.decduck3.ironcomputing.proto.Vm.VMConfiguration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.decduck3.ironcomputing.proto.Vm.VMConfiguration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.decduck3.ironcomputing.proto.Vm.VMConfiguration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.decduck3.ironcomputing.proto.Vm.VMConfiguration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.decduck3.ironcomputing.proto.Vm.VMConfiguration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.decduck3.ironcomputing.proto.Vm.VMConfiguration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.decduck3.ironcomputing.proto.Vm.VMConfiguration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.decduck3.ironcomputing.proto.Vm.VMConfiguration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.decduck3.ironcomputing.proto.Vm.VMConfiguration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.decduck3.ironcomputing.proto.Vm.VMConfiguration prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.decduck3.ironcomputing.proto.VMConfiguration}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.decduck3.ironcomputing.proto.VMConfiguration)
        com.decduck3.ironcomputing.proto.Vm.VMConfigurationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.decduck3.ironcomputing.proto.Vm.internal_static_com_decduck3_ironcomputing_proto_VMConfiguration_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.decduck3.ironcomputing.proto.Vm.internal_static_com_decduck3_ironcomputing_proto_VMConfiguration_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.decduck3.ironcomputing.proto.Vm.VMConfiguration.class, com.decduck3.ironcomputing.proto.Vm.VMConfiguration.Builder.class);
      }

      // Construct using com.decduck3.ironcomputing.proto.Vm.VMConfiguration.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        vmId_ = "";
        firmwareId_ = "";
        ramSize_ = 0L;
        harddiskIds_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.decduck3.ironcomputing.proto.Vm.internal_static_com_decduck3_ironcomputing_proto_VMConfiguration_descriptor;
      }

      @java.lang.Override
      public com.decduck3.ironcomputing.proto.Vm.VMConfiguration getDefaultInstanceForType() {
        return com.decduck3.ironcomputing.proto.Vm.VMConfiguration.getDefaultInstance();
      }

      @java.lang.Override
      public com.decduck3.ironcomputing.proto.Vm.VMConfiguration build() {
        com.decduck3.ironcomputing.proto.Vm.VMConfiguration result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.decduck3.ironcomputing.proto.Vm.VMConfiguration buildPartial() {
        com.decduck3.ironcomputing.proto.Vm.VMConfiguration result = new com.decduck3.ironcomputing.proto.Vm.VMConfiguration(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.decduck3.ironcomputing.proto.Vm.VMConfiguration result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.vmId_ = vmId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.firmwareId_ = firmwareId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.ramSize_ = ramSize_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          harddiskIds_.makeImmutable();
          result.harddiskIds_ = harddiskIds_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.decduck3.ironcomputing.proto.Vm.VMConfiguration) {
          return mergeFrom((com.decduck3.ironcomputing.proto.Vm.VMConfiguration)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.decduck3.ironcomputing.proto.Vm.VMConfiguration other) {
        if (other == com.decduck3.ironcomputing.proto.Vm.VMConfiguration.getDefaultInstance()) return this;
        if (other.hasVmId()) {
          vmId_ = other.vmId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getFirmwareId().isEmpty()) {
          firmwareId_ = other.firmwareId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getRamSize() != 0L) {
          setRamSize(other.getRamSize());
        }
        if (!other.harddiskIds_.isEmpty()) {
          if (harddiskIds_.isEmpty()) {
            harddiskIds_ = other.harddiskIds_;
            bitField0_ |= 0x00000008;
          } else {
            ensureHarddiskIdsIsMutable();
            harddiskIds_.addAll(other.harddiskIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                vmId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                firmwareId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                ramSize_ = input.readUInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureHarddiskIdsIsMutable();
                harddiskIds_.add(s);
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object vmId_ = "";
      /**
       * <code>optional string vm_id = 1;</code>
       * @return Whether the vmId field is set.
       */
      public boolean hasVmId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string vm_id = 1;</code>
       * @return The vmId.
       */
      public java.lang.String getVmId() {
        java.lang.Object ref = vmId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          vmId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string vm_id = 1;</code>
       * @return The bytes for vmId.
       */
      public com.google.protobuf.ByteString
          getVmIdBytes() {
        java.lang.Object ref = vmId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vmId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string vm_id = 1;</code>
       * @param value The vmId to set.
       * @return This builder for chaining.
       */
      public Builder setVmId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        vmId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string vm_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVmId() {
        vmId_ = getDefaultInstance().getVmId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string vm_id = 1;</code>
       * @param value The bytes for vmId to set.
       * @return This builder for chaining.
       */
      public Builder setVmIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        vmId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object firmwareId_ = "";
      /**
       * <code>string firmware_id = 2;</code>
       * @return The firmwareId.
       */
      public java.lang.String getFirmwareId() {
        java.lang.Object ref = firmwareId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firmwareId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string firmware_id = 2;</code>
       * @return The bytes for firmwareId.
       */
      public com.google.protobuf.ByteString
          getFirmwareIdBytes() {
        java.lang.Object ref = firmwareId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firmwareId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string firmware_id = 2;</code>
       * @param value The firmwareId to set.
       * @return This builder for chaining.
       */
      public Builder setFirmwareId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        firmwareId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string firmware_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirmwareId() {
        firmwareId_ = getDefaultInstance().getFirmwareId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string firmware_id = 2;</code>
       * @param value The bytes for firmwareId to set.
       * @return This builder for chaining.
       */
      public Builder setFirmwareIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        firmwareId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long ramSize_ ;
      /**
       * <code>uint64 ram_size = 3;</code>
       * @return The ramSize.
       */
      @java.lang.Override
      public long getRamSize() {
        return ramSize_;
      }
      /**
       * <code>uint64 ram_size = 3;</code>
       * @param value The ramSize to set.
       * @return This builder for chaining.
       */
      public Builder setRamSize(long value) {

        ramSize_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 ram_size = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRamSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ramSize_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList harddiskIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureHarddiskIdsIsMutable() {
        if (!harddiskIds_.isModifiable()) {
          harddiskIds_ = new com.google.protobuf.LazyStringArrayList(harddiskIds_);
        }
        bitField0_ |= 0x00000008;
      }
      /**
       * <code>repeated string harddisk_ids = 4;</code>
       * @return A list containing the harddiskIds.
       */
      public com.google.protobuf.ProtocolStringList
          getHarddiskIdsList() {
        harddiskIds_.makeImmutable();
        return harddiskIds_;
      }
      /**
       * <code>repeated string harddisk_ids = 4;</code>
       * @return The count of harddiskIds.
       */
      public int getHarddiskIdsCount() {
        return harddiskIds_.size();
      }
      /**
       * <code>repeated string harddisk_ids = 4;</code>
       * @param index The index of the element to return.
       * @return The harddiskIds at the given index.
       */
      public java.lang.String getHarddiskIds(int index) {
        return harddiskIds_.get(index);
      }
      /**
       * <code>repeated string harddisk_ids = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the harddiskIds at the given index.
       */
      public com.google.protobuf.ByteString
          getHarddiskIdsBytes(int index) {
        return harddiskIds_.getByteString(index);
      }
      /**
       * <code>repeated string harddisk_ids = 4;</code>
       * @param index The index to set the value at.
       * @param value The harddiskIds to set.
       * @return This builder for chaining.
       */
      public Builder setHarddiskIds(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureHarddiskIdsIsMutable();
        harddiskIds_.set(index, value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string harddisk_ids = 4;</code>
       * @param value The harddiskIds to add.
       * @return This builder for chaining.
       */
      public Builder addHarddiskIds(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureHarddiskIdsIsMutable();
        harddiskIds_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string harddisk_ids = 4;</code>
       * @param values The harddiskIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllHarddiskIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureHarddiskIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, harddiskIds_);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string harddisk_ids = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHarddiskIds() {
        harddiskIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string harddisk_ids = 4;</code>
       * @param value The bytes of the harddiskIds to add.
       * @return This builder for chaining.
       */
      public Builder addHarddiskIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureHarddiskIdsIsMutable();
        harddiskIds_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.decduck3.ironcomputing.proto.VMConfiguration)
    }

    // @@protoc_insertion_point(class_scope:com.decduck3.ironcomputing.proto.VMConfiguration)
    private static final com.decduck3.ironcomputing.proto.Vm.VMConfiguration DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.decduck3.ironcomputing.proto.Vm.VMConfiguration();
    }

    public static com.decduck3.ironcomputing.proto.Vm.VMConfiguration getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VMConfiguration>
        PARSER = new com.google.protobuf.AbstractParser<VMConfiguration>() {
      @java.lang.Override
      public VMConfiguration parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<VMConfiguration> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VMConfiguration> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.decduck3.ironcomputing.proto.Vm.VMConfiguration getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HardDiskConfigurationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.decduck3.ironcomputing.proto.HardDiskConfiguration)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 size = 1;</code>
     * @return The size.
     */
    long getSize();
  }
  /**
   * Protobuf type {@code com.decduck3.ironcomputing.proto.HardDiskConfiguration}
   */
  public static final class HardDiskConfiguration extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.decduck3.ironcomputing.proto.HardDiskConfiguration)
      HardDiskConfigurationOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 1,
        /* suffix= */ "",
        "HardDiskConfiguration");
    }
    // Use HardDiskConfiguration.newBuilder() to construct.
    private HardDiskConfiguration(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private HardDiskConfiguration() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.decduck3.ironcomputing.proto.Vm.internal_static_com_decduck3_ironcomputing_proto_HardDiskConfiguration_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.decduck3.ironcomputing.proto.Vm.internal_static_com_decduck3_ironcomputing_proto_HardDiskConfiguration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration.class, com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration.Builder.class);
    }

    public static final int SIZE_FIELD_NUMBER = 1;
    private long size_ = 0L;
    /**
     * <code>uint64 size = 1;</code>
     * @return The size.
     */
    @java.lang.Override
    public long getSize() {
      return size_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (size_ != 0L) {
        output.writeUInt64(1, size_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (size_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, size_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration)) {
        return super.equals(obj);
      }
      com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration other = (com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration) obj;

      if (getSize()
          != other.getSize()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSize());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.decduck3.ironcomputing.proto.HardDiskConfiguration}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.decduck3.ironcomputing.proto.HardDiskConfiguration)
        com.decduck3.ironcomputing.proto.Vm.HardDiskConfigurationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.decduck3.ironcomputing.proto.Vm.internal_static_com_decduck3_ironcomputing_proto_HardDiskConfiguration_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.decduck3.ironcomputing.proto.Vm.internal_static_com_decduck3_ironcomputing_proto_HardDiskConfiguration_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration.class, com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration.Builder.class);
      }

      // Construct using com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        size_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.decduck3.ironcomputing.proto.Vm.internal_static_com_decduck3_ironcomputing_proto_HardDiskConfiguration_descriptor;
      }

      @java.lang.Override
      public com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration getDefaultInstanceForType() {
        return com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration.getDefaultInstance();
      }

      @java.lang.Override
      public com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration build() {
        com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration buildPartial() {
        com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration result = new com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.size_ = size_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration) {
          return mergeFrom((com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration other) {
        if (other == com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration.getDefaultInstance()) return this;
        if (other.getSize() != 0L) {
          setSize(other.getSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                size_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long size_ ;
      /**
       * <code>uint64 size = 1;</code>
       * @return The size.
       */
      @java.lang.Override
      public long getSize() {
        return size_;
      }
      /**
       * <code>uint64 size = 1;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(long value) {

        size_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 size = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000001);
        size_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.decduck3.ironcomputing.proto.HardDiskConfiguration)
    }

    // @@protoc_insertion_point(class_scope:com.decduck3.ironcomputing.proto.HardDiskConfiguration)
    private static final com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration();
    }

    public static com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HardDiskConfiguration>
        PARSER = new com.google.protobuf.AbstractParser<HardDiskConfiguration>() {
      @java.lang.Override
      public HardDiskConfiguration parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HardDiskConfiguration> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HardDiskConfiguration> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.decduck3.ironcomputing.proto.Vm.HardDiskConfiguration getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_decduck3_ironcomputing_proto_VMConfiguration_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_decduck3_ironcomputing_proto_VMConfiguration_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_decduck3_ironcomputing_proto_HardDiskConfiguration_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_decduck3_ironcomputing_proto_HardDiskConfiguration_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031ironserver/proto/vm.proto\022 com.decduck" +
      "3.ironcomputing.proto\"l\n\017VMConfiguration" +
      "\022\022\n\005vm_id\030\001 \001(\tH\000\210\001\001\022\023\n\013firmware_id\030\002 \001(" +
      "\t\022\020\n\010ram_size\030\003 \001(\004\022\024\n\014harddisk_ids\030\004 \003(" +
      "\tB\010\n\006_vm_id\"%\n\025HardDiskConfiguration\022\014\n\004" +
      "size\030\001 \001(\004b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_decduck3_ironcomputing_proto_VMConfiguration_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_com_decduck3_ironcomputing_proto_VMConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_decduck3_ironcomputing_proto_VMConfiguration_descriptor,
        new java.lang.String[] { "VmId", "FirmwareId", "RamSize", "HarddiskIds", });
    internal_static_com_decduck3_ironcomputing_proto_HardDiskConfiguration_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_com_decduck3_ironcomputing_proto_HardDiskConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_decduck3_ironcomputing_proto_HardDiskConfiguration_descriptor,
        new java.lang.String[] { "Size", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
